export const FETCH_CATEGORY_REQUESTED = 'FETCH_CATEGORY_REQUESTED';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';

export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_CATEGORY_ITEMS_REQUESTED = 'FETCH_CATEGORY_ITEMS_REQUESTED';
export const FETCH_CATEGORY_ITEMS_SUCCESS = 'FETCH_CATEGORY_ITEMS_SUCCESS';
export const FETCH_CATEGORY_ITEMS_FAILURE = 'FETCH_CATEGORY_ITEMS_FAILURE';

export const DETAILS_ITEM_REQUESTED = 'DETAILS_ITEM_REQUESTED';
export const DETAILS_ITEM_SUCCESS = 'DETAILS_ITEM_SUCCESS';
export const DETAILS_ITEM_FAILURE = 'DETAILS_ITEM_FAILURE';

export const ADD_FAVOURITE = 'ADD_FAVOURIT';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
